stages:
  - build
  - deploy

# 打包镜像
build:
  stage: build
  image: xxxx.docker:xxxx
  before_script:
    - echo "${DOCKER_PASSWORD}" | docker login "${DOCKER_REGISTRY}" -u="${DOCKER_USERNAME}" --password-stdin
  script:
    - /bin/sh makefile.sh

  only:
    refs:
      - master
    changes:
      - Dockerfile
      - scripts/lego.sh
      - makefile.sh
      - .version

gen:
  stage: deploy
  image: ${DOCKER_REGISTRY}/rk-devops/lego-tls-certs-generator:v1.0.6
  script:
    - /usr/bin/lego.sh
  only:
    refs:
      - /^(aliyun|qcloud)\/.*$/
